In [3]:
import numpy as np

#1.Numpy的数组类型

In [38]:
array = [1,2,3,4,5]

In [13]:
array

[1, 2, 3, 4, 5]

In [14]:
type(array)

list

In [16]:
array+1

TypeError: can only concatenate list (not "int") to list

In [20]:
nparray = np.array([1,2,3,4,5])

In [21]:
nparray

array([1, 2, 3, 4, 5])

In [22]:
type(nparray)

numpy.ndarray

In [23]:
nparray+1

array([2, 3, 4, 5, 6])

In [24]:
nparray+nparray

array([ 2,  4,  6,  8, 10])

#2.ndarray结构、

In [26]:
list_ = [1,2,3,4]

In [27]:
array_ = np.array(list_)

In [28]:
array_

array([1, 2, 3, 4])

In [29]:
array_.dtype

dtype('int32')

In [30]:
list_ = [1,2,3,4.0]
array_ = np.array(list_)
array_

array([1., 2., 3., 4.])

In [31]:
array_.dtype

dtype('float64')

In [32]:
array_.size

4

In [34]:
array_.ndim

1

In [36]:
array_.fill(0)

In [37]:
array_

array([0., 0., 0., 0.])

#3索引和切片

In [39]:
list_ = [1,2,3,4.0]
array_ = np.array(list_)
array_

array([1., 2., 3., 4.])

In [40]:
array_[0]

1.0

In [41]:
array_[-1]

4.0

In [42]:
array_[0:2]#0到2 2不取

array([1., 2.])

In [43]:
array_[:-1]

array([1., 2., 3.])

In [44]:
array_[-3:]

array([2., 3., 4.])

In [51]:
array_=np.array([[1,2,3,],[4,5,6],[7,8,9]])
array_

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
array_.shape

(3, 3)

In [53]:
array_.size

9

In [54]:
array_.ndim

2

In [55]:
array_[1,1]

5

In [56]:
array_[1,1]=10
array_

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [57]:
array_[1]#按行取第一行

array([ 4, 10,  6])

In [58]:
array_[:,1]#按列取第一列

array([ 2, 10,  8])

In [59]:
array_[:,-1]#按列取最后一列

array([3, 6, 9])

In [64]:
array_[:,1:3]#按列取第二到第三列

array([[ 2,  3],
       [10,  6],
       [ 8,  9]])

In [65]:
array_[0:2,1:3]#前两行 后两列

array([[ 2,  3],
       [10,  6]])

#数组赋值用copy的操作

In [66]:
array2 = array_.copy()

In [67]:
array_ = np.arange(1,100)

In [68]:
array_

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
array_ = np.arange(1,100,10)

In [9]:
array_

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [11]:
mask = np.array([1,0,0,1,0,6,0,2,4,2],dtype=bool)
mask

array([ True, False, False,  True, False,  True, False,  True,  True,
        True])

In [12]:
array_[mask]

array([ 1, 31, 51, 71, 81, 91])

#构造随机数

In [13]:
random_array =np.random.rand(10)
random_array

array([0.28353403, 0.32544677, 0.7866144 , 0.1573409 , 0.96472269,
       0.90590738, 0.21728586, 0.85853116, 0.85083449, 0.85404118])

In [14]:
random_array =np.random.randint(-1,10)#左边最小值，右边最大值
random_array

7

In [16]:
random_array =np.random.randint(1,10,size=(3,3))  #构造矩阵
random_array

array([[8, 6, 5],
       [9, 8, 9],
       [1, 4, 3]])

In [18]:
np.sum(random_array) #所有数组求和

53

In [19]:
np.sum(random_array,axis=0)    #按照第一个维度进行求和，按行求和，把每一列加在一起

array([18, 18, 17])

In [21]:
np.sum(random_array,axis=1)    #按照第一个维度进行求和，按列求和，把每一行加在一起

array([19, 26,  8])

In [22]:
random_array.ndim  #求维度

2

#其他的一些函数

In [25]:
random_array=np.random.randint(1,5,size=(2,2))

In [26]:
random_array

array([[2, 2],
       [3, 4]])

In [28]:
random_array.prod() #所有元素求乘积 2*2*3*4

48

In [30]:
random_array.prod(axis=0) #第一个维度上求乘积，每列元素相乘放在行上

array([6, 8])

In [31]:
random_array.prod(axis=1) #第二个维度上求乘积

array([ 4, 12])

In [32]:
random_array.min()#求最大最小值

2

In [34]:
random_array.min(axis=0)#求第一个维度上的最小值

array([2, 2])

In [36]:
random_array.max()

4

In [37]:
random_array.argmin()#求最小值得索引，也可以加维度axis=0

0

In [38]:
random_array.argmax()#求最大值得索引

3

In [39]:
random_array.mean()#求均值

2.75

In [40]:
random_array.mean(axis=0)#求第一维度的均值

array([2.5, 3. ])

#排序

In [41]:
random_array =np.random.randint(1,5,size=(2,5))  #构造矩阵
random_array

array([[4, 4, 1, 3, 3],
       [4, 4, 3, 3, 2]])

In [42]:
np.sort(random_array)#默认按照最后一个维度排序

array([[1, 3, 3, 4, 4],
       [2, 3, 3, 4, 4]])

In [44]:
np.sort(random_array,axis=0)#按照第一个维度排序

array([[4, 4, 1, 3, 2],
       [4, 4, 3, 3, 3]])

In [45]:
np.sort(random_array,axis=1)#按照第二个维度排序

array([[1, 3, 3, 4, 4],
       [2, 3, 3, 4, 4]])

In [46]:
random_array.shape #数组形状

(2, 5)

In [47]:
random_array.shape =10#直接改变数组形状为一维

In [48]:
random_array

array([4, 4, 1, 3, 3, 4, 4, 3, 3, 2])

In [49]:
random_array.shape =5,2#改变数组形状维5行2列  先拉平再变

In [50]:
random_array

array([[4, 4],
       [1, 3],
       [3, 4],
       [4, 3],
       [3, 2]])

In [52]:
random_array.T   #矩阵的转置 直接用T

array([[4, 1, 3, 4, 3],
       [4, 3, 4, 3, 2]])

#矩阵的连接

In [53]:
array1 =np.random.randint(10,size=(2,5))
array1

array([[6, 5, 0, 4, 4],
       [2, 4, 8, 3, 7]])

In [54]:
array2 =np.random.randint(10,size=(2,5))
array2

array([[5, 4, 7, 5, 6],
       [9, 0, 4, 0, 6]])

In [55]:
array3 = np.concatenate((array1,array2))#默认按行进行拼接
array3

array([[6, 5, 0, 4, 4],
       [2, 4, 8, 3, 7],
       [5, 4, 7, 5, 6],
       [9, 0, 4, 0, 6]])

In [57]:
array3 = np.concatenate((array1,array2),axis=0)#默认按行进行拼接,也就是这个按第一个维度进行拼接
array3

array([[6, 5, 0, 4, 4],
       [2, 4, 8, 3, 7],
       [5, 4, 7, 5, 6],
       [9, 0, 4, 0, 6]])

In [58]:
array3 = np.concatenate((array1,array2),axis=1)#按第二个维度进行拼接
array3

array([[6, 5, 0, 4, 4, 5, 4, 7, 5, 6],
       [2, 4, 8, 3, 7, 9, 0, 4, 0, 6]])

#常用的生成函数

In [59]:
np.zeros(3)#构造全0矩阵

array([0., 0., 0.])

In [60]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
np.ones((3,3))#构造全1矩阵

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#矩阵的乘法

In [63]:
x=np.arange(0,2)#从0数到1

In [64]:
y=np.arange(2,4)#从2数到3

In [65]:
x,y

(array([0, 1]), array([2, 3]))

In [67]:
x*y#里面元素每个相乘

array([0, 3])

#等于np.multipty(x,y) #点乘

In [70]:
x = np.arange(0,6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [71]:
y = np.arange(0,6).reshape(3,2)
y

array([[0, 1],
       [2, 3],
       [4, 5]])

In [72]:
np.dot(x,y)#我学过的矩阵的乘法（线性代数的）

array([[10, 13],
       [28, 40]])